// UI strings per language
module.exports = {
  vi: {
    nav_home: "Trang chủ",
    nav_blog: "Blog",
    hero_role: "CEO · Security Expert · Bug Bounty Hunter",
    hero_biz:
      "Nhà sáng lập & CEO Công ty TNHH Hòa bình Không gian mạng (CyPeace). Phát triển sản phẩm và cung cấp dịch vụ an ninh mạng, an toàn thông tin.",
    hero_intro:
      "Săn lỗ hổng bảo mật tại Synack Red Team. Được vinh danh bởi Apple, Google, Meta, Microsoft và nhiều tổ chức khác.",
    wb_title: "Wanted Board",
    wb_sub: "The entrepreneurship bounty trail",
    wb_captured: "Captured",
    wb_in_progress: "In progress",
    wb_locked: "Locked",
    wb_tab_achieved: "Đã đạt",
    wb_tab_progress: "Đang tiến hành",
    wb_tab_locked: "Chưa mở khóa",
    latest_posts: "Bài viết mới nhất",
    all_posts: "Tất cả bài viết →",
    recognition: "Vinh danh & Hall of Fame",
    certs: "Chứng chỉ",
    press_title: "Truyền Thông",
    press_read: "Đọc bài",
    gallery: "Hacker Hangout",
    gallery_sub: "POV · Đời & Nghề",
    gallery_shuffle: "Ngẫu nhiên",
    gallery_count_aria: "Số ảnh hiển thị",
    verify: "Xác minh",
    pinned_label: "Thành tựu đỉnh cao",
    view_acropolis: "Xem trên Acropolis",
    hall_of_fame_label: "Halls of Fame",
    hover_hint: "Di chuột để xác minh",
    view_hint: "Bấm để xem ảnh",
    read_more: "Đọc tiếp",
    min_read: "phút đọc",
    blog_title: "Blog",
    blog_desc: "Writing cyber security & Startup.",
    search_placeholder: "Tìm theo tiêu đề hoặc #tag…",
    no_results: "Không tìm thấy bài viết nào.",
    blog_empty: "Chưa có bài viết nào. Hãy quay lại sau nhé!",
    filtering_tag: "Đang lọc theo tag",
    clear: "Xóa",
    results_count: "bài viết",
    back_to_blog: "← Quay lại Blog",
    switch_lang: "EN",
    footer_built: "Dựng bằng Eleventy · Host trên GitHub Pages",
  },
  en: {
    nav_home: "Home",
    nav_blog: "Blog",
    hero_role: "CEO · Security Expert · Bug Bounty Hunter",
    hero_biz:
      "Founder & CEO of Cyberspace Peace Company Limited (CyPeace). Building cybersecurity products and providing professional security services.",
    hero_intro:
      "Hunting high-impact vulnerabilities with the Synack Red Team. Recognized by Apple, Google, Meta, Microsoft and many more.",
    wb_title: "Wanted Board",
    wb_sub: "The entrepreneurship bounty trail",
    wb_captured: "Captured",
    wb_in_progress: "In progress",
    wb_locked: "Locked",
    wb_tab_achieved: "Achieved",
    wb_tab_progress: "In Progress",
    wb_tab_locked: "Locked",
    latest_posts: "Latest posts",
    all_posts: "All posts →",
    recognition: "Recognition & Halls of Fame",
    certs: "Certifications",
    press_title: "In The Press",
    press_read: "Read article",
    gallery: "Hacker Hangout",
    gallery_sub: "POV · Life & Work",
    gallery_shuffle: "Shuffle",
    gallery_count_aria: "Number of photos to show",
    verify: "Verify",
    pinned_label: "Top Achievement",
    view_acropolis: "View on Acropolis",
    hall_of_fame_label: "Halls of Fame",
    hover_hint: "Hover to verify",
    view_hint: "Click to view image",
    read_more: "Read more",
    min_read: "min read",
    blog_title: "Blog",
    blog_desc: "Writing cyber security & Startup.",
    search_placeholder: "Search by title or #tag…",
    no_results: "No posts found.",
    blog_empty: "No posts yet. Check back soon!",
    filtering_tag: "Filtering by tag",
    clear: "Clear",
    results_count: "posts",
    back_to_blog: "← Back to Blog",
    switch_lang: "VI",
    footer_built: "Built with Eleventy · Hosted on GitHub Pages",
  },
};
